wp-content/themes/performance360/.gitignore
wp-content/themes/performance360/functions.php
wp-content/themes/performance360/index.php
wp-content/themes/performance360/lib/helpers.php

ad excerpt to loop, functions, helpers, post_meta function

basic(front) :: ad excerpt to loop, functions, helpers

---

README.md
wp-content/themes/performance360-child/bundle.css
wp-content/themes/performance360-child/functions.php
wp-content/themes/performance360-child/style.css
wp-content/themes/performance360/functions.php

create childtheme and some basics for it

chore(child-theme) :: create childtheme and some basics for it

---

wp-content/themes/performance360/lib/sidebars.php

Add function adn action to init primary sidebar which will appears in home, category, search pages

feat(func) :: init primary sidebar in lib/sidebars.php

---

wp-content/themes/performance360/lib/sidebars.php
wp-content/themes/performance360/sidebar.php

add right isdebar to main template and do content full width if there are no widgets in it

add right isdebar to main template

---

wp-content/themes/performance360/footer.php
wp-content/themes/performance360/functions.php
wp-content/themes/performance360/index.php
wp-content/themes/performance360/lib/sidebars.php
wp-content/themes/performance360/sidebar.php

Add footer layout, register widgets and add function to calculate footer columns depending on footer sidebars count

Basiс footer layout and widgets

---

wp-content/themes/performance360/footer.php
wp-content/themes/performance360/functions.php

correct some stuff in function which counts footer widgets

correct some stuff in function which counts footer widgets

---

wp-content/themes/performance360/footer.php
wp-content/themes/performance360/functions.php
wp-content/themes/performance360/header.php
wp-content/themes/performance360/lib/theme_support.php

feat(layout) :: add header layout and theme_support file

feat(layout) :: add header layout and theme_support file

---

wp-content/themes/performance360/header.php
wp-content/themes/performance360/searchform.php
wp-content/themes/performance360/template-parts/mob_searchform.php

feat(struct) :: add mob and desct searchforms

feat(struct) :: add mob and desct searchforms

---

wp-content/themes/performance360/lib/navigation.php

feat(funct) :: add icons to dropdown

feat(funct) :: add icons to dropdown

---

wp-content/themes/performance360/functions.php
wp-content/themes/performance360/lib/customize.php
wp-content/themes/performance360/loop-index.php
wp-content/themes/performance360/template-parts/footer/info.php

feat(layout) : add two column layout in main loop

feat(layout) : add two column layout in main loop

---

wp-content/themes/performance360/functions.php
wp-content/themes/performance360/home.php
wp-content/themes/performance360/index.php
wp-content/themes/performance360/lib/metaboxes.php
wp-content/themes/performance360/loop-index.php
wp-content/themes/performance360/template-parts/post/content-big_post.php
wp-content/themes/performance360/template-parts/post/content-masonry.php

feat(funct) :: add big medium posts meta fileds

feat(funct) :: add big medium posts meta fileds

---

wp-content/themes/performance360/src/assets/js/bundle.js
wp-content/themes/performance360/src/assets/js/components/owl.js
wp-content/themes/performance360/src/assets/scss/bundle.scss

Adding https://github.com/OwlCarousel2/OwlCarousel2 to the project

chore(owl) :: add owl carousel js and css

---

wp-content/themes/performance360/package.json
wp-content/themes/performance360/src/assets/js/components/owl.js
wp-content/themes/performance360/src/assets/scss/bundle.scss
wp-content/themes/performance360/src/assets/scss/components/navigation/_main-navigation.scss
wp-content/themes/performance360/template-parts/navigation/main_navigation.php

Implements mobile menu using the owl carousel with `autoWidth` property
http://owlcarousel2.github.io/OwlCarousel2/demos/basic.html

chore(mobile menu carousel) :: implementation

---

wp-content/themes/performance360/src/assets/js/components/navigation.js
wp-content/themes/performance360/src/assets/scss/components/_header.scss
wp-content/themes/performance360/template-parts/header/mob_searchform.php

feat(search) :: add mobile search func

---

.gitignore
wp-content/themes/performance360/src/assets/js/components/navigation.js
wp-content/themes/performance360/src/assets/js/components/owl.js
wp-content/themes/performance360/src/assets/scss/components/navigation/_main-navigation.scss
wp-content/themes/performance360/template-parts/navigation/main_navigation.php

add dropdown menu for desktops

feat(more) :: add more dropdown

---

wp-content/themes/performance360/src/assets/js/components/navigation.js
wp-content/themes/performance360/src/assets/scss/components/navigation/_main-navigation.scss

Fix func of the `view more` menu when resizing from small to large

bug(more menu) :: resize from small to large fix

---

wp-content/themes/performance360/header.php
wp-content/themes/performance360/src/assets/js/components/navigation.js
wp-content/themes/performance360/src/assets/scss/components/navigation/_top-navigation.scss

feat(hamburger menu) :: hamburger menu implementation

---

wp-content/themes/performance360/home.php
wp-content/themes/performance360/src/assets/js/components/owl.js
wp-content/themes/performance360/src/assets/scss/bundle.scss
wp-content/themes/performance360/src/assets/scss/components/_bottom-slider.scss
wp-content/themes/performance360/src/assets/scss/components/navigation/_main-navigation.scss
wp-content/themes/performance360/src/assets/scss/owl/_animate.scss
wp-content/themes/performance360/src/assets/scss/owl/_autoheight.scss
wp-content/themes/performance360/src/assets/scss/owl/_core.scss
wp-content/themes/performance360/src/assets/scss/owl/_lazyload.scss
wp-content/themes/performance360/src/assets/scss/owl/_theme.default.scss
wp-content/themes/performance360/src/assets/scss/owl/_theme.green.scss
wp-content/themes/performance360/src/assets/scss/owl/_theme.scss
wp-content/themes/performance360/src/assets/scss/owl/_video.scss
wp-content/themes/performance360/src/assets/scss/owl/owl.carousel.scss
wp-content/themes/performance360/src/assets/scss/owl/owl.theme.default.scss
wp-content/themes/performance360/src/assets/scss/owl/owl.theme.green.scss
wp-content/themes/performance360/template-parts/post/content-slider.php

feat(bottom-slider) :: add bottom slider with owl

---

wp-content/themes/performance360/functions.php
wp-content/themes/performance360/loop-page.php
wp-content/themes/performance360/src/assets/js/load-more.js

feat(func) :: add loadmore ajax on tags pages

feat(func) :: add loadmore ajax on tags pages

---

wp-content/themes/performance360/src/assets/js/components/navigation.js

Fixes broken menu element class

bug(main menu) :: fix class

---

wp-content/themes/performance360/functions.php
wp-content/themes/performance360/lib/helpers.php
wp-content/themes/performance360/src/assets/scss/components/_post.scss

- fixes tags on homepage
- style fixes on homepage

Homepage tags css

---

wp-content/themes/performance360/functions.php
wp-content/themes/performance360/src/assets/scss/components/_post.scss

chore(tags) :: style adjustments

---

wp-content/themes/performance360/home.php
wp-content/themes/performance360/lib/customize.php

add field to home page admin that defines the number of slider posts

Limit number of slider posts

---

wp-content/themes/performance360/functions.php
wp-content/themes/performance360/lib/sidebar_pop_posts_widget.php
wp-content/themes/performance360/loop-single.php
wp-content/themes/performance360/src/assets/scss/components/_widget.scss

pop posts widget in sidebar + post view count func in functions PHP

feat(sidebar) :: pop posts widget

---

wp-content/themes/performance360/footer.php
wp-content/themes/performance360/lib/subscribe-widget.php
wp-content/themes/performance360/src/assets/js/bundle.js
wp-content/themes/performance360/src/assets/js/components/send-subscribe.js
wp-content/themes/performance360/src/assets/scss/bundle.scss
wp-content/themes/performance360/src/assets/scss/components/_popup.scss

feat(func) :: add basic subscribe func

feat(func) :: add basic subscribe func

---

wp-content/themes/performance360/functions.php
wp-content/themes/performance360/single.php
wp-content/themes/performance360/src/assets/scss/bundle.scss
wp-content/themes/performance360/src/assets/scss/components/_media.scss
wp-content/themes/performance360/src/assets/scss/components/_page.scss
wp-content/themes/performance360/src/assets/scss/settings/_typography.scss

feat(func) :: add related post dunc style and layout

feat(func) :: add related post dunc style and layout

---

wp-content/themes/performance360/comments.php
wp-content/themes/performance360/functions.php
wp-content/themes/performance360/lib/comment-callback.php
wp-content/themes/performance360/lib/enqueue_assets.php
wp-content/themes/performance360/lib/related-posts.php
wp-content/themes/performance360/loop-search.php
wp-content/themes/performance360/search.php
wp-content/themes/performance360/single.php
wp-content/themes/performance360/src/assets/js/load-more.js
wp-content/themes/performance360/src/assets/scss/bundle.scss
wp-content/themes/performance360/src/assets/scss/components/_comment.scss
wp-content/themes/performance360/src/assets/scss/components/_comments.scss
wp-content/themes/performance360/src/assets/scss/components/_page.scss
wp-content/themes/performance360/src/assets/scss/components/_post-related.scss
wp-content/themes/performance360/src/assets/scss/components/navigation/_main-navigation.scss
wp-content/themes/performance360/template-parts/single/loop-related.php

feat(cooment) :: add comments form and basic layout

feat(cooment) :: add comments form and basic layout

---

wp-content/themes/performance360/lib/comment-callback.php
wp-content/themes/performance360/src/assets/scss/components/_comments.scss

feat(style) add comments style

feat(style) add comments style

---

wp-content/themes/performance360/src/assets/scss/components/_bottom-slider.scss
wp-content/themes/performance360/src/assets/scss/components/_load-more.scss
wp-content/themes/performance360/src/assets/scss/components/_post.scss
wp-content/themes/performance360/src/assets/scss/components/_widget.scss

more style changes

---

wp-content/themes/performance360/src/assets/scss/components/_bottom-slider.scss

- bottom slider width to content

more style fixes

---

wp-content/themes/performance360/home.php
wp-content/themes/performance360/src/assets/scss/components/_bottom-slider.scss

slider improvements

---

wp-content/themes/performance360/home.php
wp-content/themes/performance360/lib/helpers.php
wp-content/themes/performance360/lib/posts-widget.php
wp-content/themes/performance360/src/assets/scss/components/_media.scss
wp-content/themes/performance360/src/assets/scss/components/_page.scss
wp-content/themes/performance360/src/assets/scss/components/_post.scss
wp-content/themes/performance360/src/assets/scss/settings/_colours.scss
wp-content/themes/performance360/src/assets/scss/settings/_typography.scss
wp-content/themes/performance360/template-parts/post/content-masonry.php
wp-content/themes/performance360/template-parts/post/content-page.php

chore(bugs) fix some bugs

---

wp-content/themes/performance360/src/assets/scss/components/_bottom-slider.scss

fixe some type styles and name

chore(slider) :: more style fixes

---

wp-content/themes/performance360/comments.php
wp-content/themes/performance360/functions.php
wp-content/themes/performance360/lib/helpers.php
wp-content/themes/performance360/lib/posts-widget.php
wp-content/themes/performance360/lib/sidebar_pop_posts_widget.php
wp-content/themes/performance360/src/assets/js/components/send-subscribe.js
wp-content/themes/performance360/src/assets/scss/components/_header.scss
wp-content/themes/performance360/src/assets/scss/components/_media.scss
wp-content/themes/performance360/src/assets/scss/components/_post.scss
wp-content/themes/performance360/template-parts/post/content-page.php
wp-content/themes/performance360/template-parts/post/content-slider.php

chore(bugs) :: fix additional bugs on dev server

chore(bugs) :: fix additional bugs on dev server

---

wp-content/themes/performance360/loop-page.php
wp-content/themes/performance360/src/assets/scss/components/_post.scss

Fix single title

---

wp-content/themes/performance360/functions.php
wp-content/themes/performance360/src/assets/scss/components/_bottom-slider.scss
wp-content/themes/performance360/src/assets/scss/components/_comments.scss
wp-content/themes/performance360/src/assets/scss/components/_post-related.scss
wp-content/themes/performance360/src/assets/scss/components/_post.scss
wp-content/themes/performance360/template-parts/post/content-single.php

feat(leayout) add new fixes to layout on different elements

feat(leayout) add new fixes to layout on different elements

---

wp-content/themes/performance360/src/assets/scss/components/_post.scss
wp-content/themes/performance360/template-parts/post/content-big_post.php

chore(bugs) fix label padding
